name: Clair # Name of the Catalog Entry
description: |
  Clair (Container Vulnerability Analysis Service)
# Description of the Catalog Entry
version: 0.1 # Version of the Catalog to be used
category: Community # Category to be used for searching catalog entries
maintainer: Yu You <youyu.youyu@gmail.com> # The maintainer of the catalog entry
license: Apache License Version 2.0 # The license
projectURL: https://github.com/coreos/clair # A URL related to the catalog entry
